<?php

namespace App;


use App\Events\PostCreated;

class Post extends Model
{
    protected $dispatchesEvents = [
        'created' => PostCreated::class
    ];
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub May be return 'slug' для символьного кода
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function owner()
    {
        return $this->belongsTo(User::class);
    }

}
